bizunited/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
import users.urls as user_urls
import startups.urls as startup_urls
import investors.urls as investor_urls
import communications.urls as messaging_urls
import consultants.urls as consultant_urls
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/', include(user_urls)),
    path('startups/', include(startup_urls)),
    path('investors/', include(investor_urls)),
    path('messaging/', include(messaging_urls)),
    path('consult/', include(consultant_urls )),
    path('profile/', views.userProfile, name='user-profile'),
    path('pitches/', views.globalPitches, name='global-pitches'),
    path('pitch/<str:pk>/', views.pitchDetailView, name='single-pitch'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('onboarding/create-profile/', views.profileCreation, name='onboarding-profile'),
    path('onboarding/entrepreneur/', views.onboardingEnt, name='onboarding-entrepreneur'),
    path('onboarding/investor/', views.onboardingInv, name='onboarding-investor'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Profile(models.Model):
    ROLE_VALUE = (
        ('inv', 'Investor'),
        ('ent', 'Entrepreneur'),
        ('con', 'Consultant')
        )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    role = models.CharField(max_length=200, choices=ROLE_VALUE)
    first_name = models.CharField(max_length=80, null=True, blank=True)
    last_name = models.CharField(max_length=80, null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True, upload_to='profile_pictures/', default='profile_pictures/default.jpg')
    bio = models.TextField(blank=True, null=True)
    socials_linkedin = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)

    def __str__(self):
        return self.username

class Entrepreneur(models.Model):
    STAGES = (
        ('none', 'None'),
        ('pre_seed', 'Pre-Seed'),
        ('seed', 'Seed'),
        ('series_a', 'Series A'),
        ('series_b', 'Series B'),
        ('series_c', 'Series C'),
        ('series_d', 'Series D'),
    )

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    startup = models.CharField(max_length=100, null=True, blank=True)
    org_position = models.CharField(max_length=100, null=True, blank=True)
    industry = models.CharField(max_length=100, null=True, blank=True)
    education = models.CharField(max_length=100, null=True, blank=True)
    investment_stage =  models.CharField(max_length=200, choices=STAGES, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)

    def __str__(self):
        return self.profile.username

class Investor(models.Model):
    STAGES = (
        ('pre_seed', 'Pre-Seed'),
        ('seed', 'Seed'),
        ('series_a', 'Series A'),
        ('series_b', 'Series B'),
        ('series_c', 'Series C'),
        ('series_d', 'Series D'),
    )

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    organization = models.CharField(max_length=100, null=True, blank=True)
    org_position = models.CharField(max_length=100, null=True, blank=True)
    preferred_stage =  models.CharField(max_length=200, choices=STAGES, null=True, blank=True)
    investment_focus = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)

class Consultant(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)



    

templates/detail-pitch.html
{% extends "main.html" %}
{% load static %}
{% block content %}
<div class="flex">
    {% include "side-nav-ent.html" %}
    
    <div class="flex items-center justify-center w-[100%]">
        <div class="bg-[#f7f7f8] rounded-xl w-[88%]">
            

            <div class="bg-white relative shadow rounded-lg w-5/6 md:w-5/6  lg:w-4/6 xl:w-3/6 mx-auto mt-24">
                <div class="flex justify-center">
                    {% if pitch.image %}
                        <img src="{{pitch.image.url}}" alt="" class="rounded-full mx-auto absolute -top-20 w-32 h-32 shadow-md border-4 border-white transition duration-200 transform hover:scale-110">
                    {% endif %}
                </div>
                
                <div class="mt-16 px-6">
                    <h1 class="font-bold text-center text-3xl text-gray-900 mb-4">{{pitch.title}}</h1>
                    <p class="text-center text-sm text-gray-400 font-medium mt-1">{{pitch.description | slice:150}}...</p>
                

                    <div class="w-full">
                        {% comment %} <h3 class="font-medium text-gray-900 text-left px-6">Profile Details:</h3> {% endcomment %}
                        <div class="mt-5 w-full flex flex-col items-center overflow-hidden text-sm">
                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                    <span class="font-bold">Investment Stage</span> : {{pitch.get_investment_stage_display}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Industry</span> : {{pitch.industry}}
                            </a>

                        </div>
                    </div>
                </div>
            </div>

            <div class="my-12 flex items-center justify-center">
              <a href="{% url 'sendMessage' pitch.entrepreneur.profile.id %}" class="mx-2">
                    <button type="button" id="submit" class="py-2.5 px-5 text-xl font-semibold tracking-wider rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none cursor-pointer">
                      Connect <i class="fa-solid fa-handshake"></i>
                    </button>
                </a>
                {% if request.user.profile.investor %}
                <a href="{% url 'add-watchlist-item' pitch.id %}">
                    <button type="button" id="submit" class="py-2.5 px-5 text-xl font-semibold tracking-wider rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none cursor-pointer">
                        Watchlist <i class="fa-solid fa-eye"></i>
                    </button>
                </a>
                {% endif %}
            </div>
            
        </div> 
    </div>
</div>

{% endblock content %}

templates/list-pitches.html
{% extends "main.html" %} {% block content %}
<div class="flex gap-8">
  {% if user.profile.entrepreneur %}
  {% include "side-nav-ent.html" %}
  {% elif user.profile.investor %}
  {% include "side-nav-inv.html" %}
  {% endif %}

  <div class="container mx-auto p-6">
    <form class="max-w-md mx-auto" action="">
      <label
        for="default-search"
        class="mb-2 text-sm font-medium text-gray-900 sr-only"
        >Search</label
      >
      <div class="relative">
        <div
          class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none"
        >
          <svg
            class="w-4 h-4 text-gray-500"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 20 20"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
            />
          </svg>
        </div>
        <input
          type="search"
          name="query"
          value="{{query}}"
          id="default-search"
          class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-purple-500 focus:border-purple-500  "
          placeholder="Search Pitches by Title, Entrepreneur..."
          required
        />
        <button
          type="submit"
          class="text-white absolute end-2.5 bottom-2.5 bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2"
        >
          Search
        </button>
      </div>
    </form>

    <div class="my-8">
      <h2 class="text-3xl font-extrabold mb-2">HOT STARTUPS 🔥</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for pitch in pitches %}
        <div
          class="bg-white shadow-[0_4px_12px_-5px_rgba(0,0,0,0.4)] border p-2 w-full max-w-sm rounded-lg font-[sans-serif] overflow-hidden mx-auto mt-4"
        >
          <div class="min-h-[245px]">
            <img
              src="{{pitch.image.url}}"
              class="w-full rounded-lg"
            />
          </div>
          <hr class="my-2">
          <div class="p-6 text-center">
            <h3 class="text-2xl font-bold mb-2">{{pitch.title}}</h3>
            <h4 class="text-xs text-gray-400">{{pitch.entrepreneur.profile.first_name}} {{pitch.entrepreneur.profile.last_name}}</h4>
            <p class="mt-3 text-sm text-gray-500 leading-relaxed">
              {{pitch.description|slice:150}}
            </p>
           
            <a href="{% url 'single-pitch' pitch.id %}">
              <button
              type="button"
              class="mt-6 px-5 py-2.5 w-full rounded-lg text-white text-sm tracking-wider font-semibold border-none outline-none bg-purple-600 hover:bg- 00"
            >
              View
            </button>
            </a>
              
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/main.html
{% load static %}
{% load tailwind_tags %}
{% tailwind_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BizUnited</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "images/favicon_io/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "images/favicon_io/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "images/favicon_io/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "images/favicon_io/site.webmanifest" %}">
    {% comment %} <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png' %}"> {% endcomment %}
    <script src="https://kit.fontawesome.com/52b9614d93.js" crossorigin="anonymous"></script>
</head>
<body>
   {% if messages %}
        {% for message in messages %}
        <div class="bg-red-100 text-red-800  p-4 rounded-lg relative w-2/3 m-auto" role="alert">
            <strong class="font-bold text-sm">Alert!</strong>
            <span class="block text-sm sm:inline max-sm:mt-2 max-sm:ml-0 ml-4 mr-8">{{message}}</span>
            <svg xmlns="http://www.w3.org/2000/svg"
            class="w-7 hover:bg-red-200 rounded-lg transition-all p-2 cursor-pointer fill-red-500 absolute right-4 top-1/2 -translate-y-1/2" viewBox="0 0 320.591 320.591">
            <path
                d="M30.391 318.583a30.37 30.37 0 0 1-21.56-7.288c-11.774-11.844-11.774-30.973 0-42.817L266.643 10.665c12.246-11.459 31.462-10.822 42.921 1.424 10.362 11.074 10.966 28.095 1.414 39.875L51.647 311.295a30.366 30.366 0 0 1-21.256 7.288z"
                data-original="#000000" />
            <path
                d="M287.9 318.583a30.37 30.37 0 0 1-21.257-8.806L8.83 51.963C-2.078 39.225-.595 20.055 12.143 9.146c11.369-9.736 28.136-9.736 39.504 0l259.331 257.813c12.243 11.462 12.876 30.679 1.414 42.922-.456.487-.927.958-1.414 1.414a30.368 30.368 0 0 1-23.078 7.288z"
                data-original="#000000" />
            </svg>
        </div>
        {% endfor %}
    {% endif %} 
    {% block content %}
       
    {% endblock %}
</body>
</html>

templates/profile.html
{% extends "main.html" %} {% load static %} {% block content %}

<div class="flex">
    {% if user.profile.entrepreneur %}
    {% include "side-nav-ent.html" %}
    {% elif user.profile.investor %}
    {% include "side-nav-inv.html" %}
    {% endif %}

  <div class="mt-16 flex items-start justify-center w-[100%]">
    <div
      class="bg-[#f7f7f8] rounded-xl w-[88%] flex-col justify-center items-center"
    >
      <a
      {% if profile.entrepreneur %}
        href="{% url 'startup-dashboard' %}"
        {% elif profile.investor%}
        href="{% url 'investor-dashboard' %}"
        {% endif %}
        class="relative top-8 left-6 rounded-full bg-purple-300 p-4"
        ><i class="fa-solid fa-angle-left text-purple-600"></i
      ></a>
      
    <div class="container mx-auto my-8">
        <div>

            <div class="bg-white relative shadow rounded-lg w-5/6 md:w-5/6  lg:w-4/6 xl:w-3/6 mx-auto">
                <div class="flex justify-center">
                    {% if profile.profile_pic %}
                        <img src="{{profile.profile_pic.url}}" alt="" class="rounded-full mx-auto absolute -top-20 w-32 h-32 shadow-md border-4 border-white transition duration-200 transform hover:scale-110">
                    {% endif %}
                </div>
                
                <div class="mt-16">
                    <h1 class="font-bold text-center text-3xl text-gray-900">{{profile.first_name}} {{profile.last_name}}</h1>
                    <p class="text-center text-sm text-gray-400 font-medium mt-1">{{profile.bio}}</p>
                    <p>
                        <span>
                            
                        </span>
                    </p>
                    <div class="my-5 px-6">
                        <a href="https://linkedin.com/in/{{profile.socials_linkedin}}" class="text-gray-200 block rounded-lg text-center font-medium leading-6 px-6 py-3 bg-purple-800 hover:bg-purple-900 hover:text-white">Connect with <span class="font-bold">@{{profile.socials_linkedin}}</span></a>
                    </div>
                    <div class="flex justify-center items-center my-5 px-6">
                        <p class="text-center text-sm text-gray-600">
                        {{profile.email}}
                        </p>
                    </div>

                    <div class="w-full">
                        {% comment %} <h3 class="font-medium text-gray-900 text-left px-6">Profile Details:</h3> {% endcomment %}
                        <div class="mt-5 w-full flex flex-col items-center overflow-hidden text-sm">
                            {% if profile.entrepreneur %}
                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                    <span class="font-bold">Organization</span> : {{profile.entrepreneur.startup}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Position</span> : {{profile.entrepreneur.org_position}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Industry</span> : {{profile.entrepreneur.industry}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Investment Stage</span> : {{profile.entrepreneur.get_investment_stage_display}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150 overflow-hidden">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Location</span> : {{profile.entrepreneur.location}}
                            </a>
                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150 overflow-hidden">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Education</span> : {{profile.entrepreneur.education}}
                            </a>


                            {% elif profile.investor %}


                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                    <span class="font-bold">Organization</span> : {{profile.investor.organization}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Position</span> : {{profile.investor.org_position}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Investment Focus</span> : {{profile.investor.investment_focus}}
                            </a>

                            <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
                                <img src="{% static 'images/favicon_io/favicon-32x32.png' %}" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                                <span class="font-bold">Preferred Stage</span> : {{profile.investor.get_preferred_stage_display}}
                            </a>

                            {% endif %}
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/side-nav-ent.html
{% load static %}
<nav
    class="bg-[#f7f7f8] bottom-0 top-0 left-0 min-w-[250px] py-6 px-4 font-[sans-serif] min-h-screen"
  >
  <div class="fixed">
    <div class="relative top-5 left-5">
      <a href="javascript:void(0)"
        ><img
          src="{% static "images/logo-no-background.png" %}"
          alt="logo"
          class="w-[160px]"
        />
      </a>
    </div>

    <div class="overflow-auto py-6 h-full mt-8">
      <ul class="space-y-1">
        <li>
          <a
            href="{% url 'startup-dashboard' %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-gauge text-xl fa-fw"></i>
          </div>
          <span>Dashboard &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
          </a>
        </li>
        <li>
          <a
            href="{% url "global-pitches" %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">
            <i class="fa-regular fa-address-card text-xl fa-fw"></i>
          </div>
            <span class="">Pitches</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'add-pitch' %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-plus text-xl fa-fw"></i>
          </div>
            <span>Add Pitch</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'inbox' %}"
            class="cursor-pointer text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-inbox text-xl fa-fw"></i>
          </div>
            <span class="">Inbox</span>
            
          </a>
        </li>
        <li>
          <a
            href="{% url 'consultant-posts' %}"
            class="cursor-pointer text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-handshake-angle text-xl fa-fw"></i>
          </div>
            <span class="">Consult</span>
            <div type="button" class="absolute right-10 flex items-center  text-red-600 text-[10px] bg-red-50 px-4 py-1.5 tracking-wide rounded-full">
              Beta
            </div>
          </a>
        </li>
        <li>
          <a
            href="{% url 'user-profile' %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-user text-xl fa-fw"></i>
          </div>
            <span>Profile</span>
          </a>
        </li>
        <li>
          <a
            href="{% url "logout" %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-right-from-bracket text-xl fa-fw"></i>
          </div>
            <span>Logout</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  </nav>

templates/side-nav-inv.html
{% load static %}
<nav
    class="bg-[#f7f7f8] bottom-0 top-0 left-0 min-w-[250px] py-6 px-4 font-[sans-serif] min-h-screen"
  >
  <div class="fixed">
    <div class="relative top-5 left-5">
      <a href="javascript:void(0)"
        ><img
          src="{% static "images/logo-no-background.png" %}"
          alt="logo"
          class="w-[160px]"
        />
      </a>
    </div>

    <div class="overflow-auto py-6 h-full mt-8">
      <ul class="space-y-1">
        <li>
          <a
            href="{% url 'investor-dashboard' %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-gauge text-xl fa-fw"></i>
          </div>
          <span>Dashboard &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
          </a>
        </li>
        <li>
          <a
            href="{% url "global-pitches" %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">
            <i class="fa-regular fa-address-card text-xl fa-fw"></i>
          </div>
            <span class="">Pitches</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'inbox' %}"
            class="cursor-pointer text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-inbox text-xl fa-fw"></i>
          </div>
            <span class="">Inbox</span>
            
          </a>
        </li>
        <li>
          <a
            href="{% url 'consultant-posts' %}"
            class="cursor-pointer text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-handshake-angle text-xl fa-fw"></i>
          </div>
            <span class="">Consult</span>
            <div type="button" class="absolute right-10 flex items-center  text-red-600 text-[10px] bg-red-50 px-4 py-1.5 tracking-wide rounded-full">
              Beta
            </div>
          </a>
        </li>
        <li>
          <a
            href="{% url 'user-profile' %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-user text-xl fa-fw"></i>
          </div>
            <span>Profile</span>
          </a>
        </li>
        <li>
          <a
            href="{% url "logout" %}"
            class="text-black hover:text-purple-600 text-[15px] flex items-center gap-6 hover:bg-white rounded px-4 py-3 transition-all"
          >
          <div class="w-3">

          <i class="fa-solid fa-right-from-bracket text-xl fa-fw"></i>
          </div>
            <span>Logout</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  </nav>